from os import getenv

URL = getenv("URL")
TOKEN = getenv("TOKEN")
SALES_ENDPOINT = getenv("SALES_ENDPOINT")
PAYMENTS_ENDPOINT = getenv("PAYMENTS_ENDPOINT")
DISCREPANCIES_ENDPOINT = getenv("DISCREPANCIES_ENDPOINT")


DOWNLOAD_PAYMENTS = True
DOWNLOAD_SALES = True
DOWNLOAD_DISCREPANCIES_DATA = False

START_DATE = "2024-1-1"
END_DATE = "2024-1-1"
